### ISSUE TITLE
New cards should announce where they are in the stack

### ISSUE THREAD

**Issue by popey** [grifferz/pah-irc#4]
Typically in play you "`hand`" once, then play a few rounds and try to keep track of where your cards are.
When you play a card, that leaves a gap, and what should happen is when you are dealt a new card, it should insert that new card(s) into the slots left by the previous play, and announce as such.

E.g.
- `<PAH>` Your White Cards in **#debug**:
- `<PAH>`  **1**. Agriculture.
- `<PAH>`  **2**. Copping a feel.
- `<PAH>`  **3**. Serfdom.
- `<PAH>`  **4**. Flightless birds.
- `<PAH>`  **5**. The Stig.
- `<PAH>`  **6**. Farting and walking away.
- `<PAH>`  **7**. Scalping the Milkybar Kid.
- `<PAH>`  **8**. Dark and mysterious forces beyond our control.
- `<PAH>`  **9**. Excalibur.
- `<PAH>`  **10**. Hurling one's body down a hill in pursuit of a wheel of cheese.
- `<popey>` 9
- `<PAH>` Thanks. So this is your play:
- `<PAH>` → What don't you want to find in your Kung Pao chicken? **Excalibur**.
- `<PAH>` **1** new White Card has been dealt to you:
- `<PAH>` → Pictures of boobs.

So I think it should say:-
- `<PAH>` **1** new White Card has been dealt to you:
- `<PAH>` → **9**. Pictures of boobs.

**Comment by grifferz** [comment]
This is tricky. Possibly because of poor database design.

There's nothing in the database which says what the number of the card is in your hand; the numbers are generated by the sequence order that the cards are selected out of the `users_games_hands` table.

When it's listing off your full hand it's doing something like this:

``` SQL
SELECT
    *
FROM
    users_games_hands
WHERE
    user = $user->id AND
    game = $game->id
ORDER BY
    wcardidx ASC
```

It's then going to iterate through the results and increment a counter so the first row is card 1, second row is card 2 and so on. That counter doesn't live in the database.

So you see, when you are given fewer than 10 cards it does not know what position they will be in your hand.

Perhaps the answer is to add a `position` field to `users_games_hands` for where that card is in the hand, and assign new cards only position numbers that have been played. I'm not sure how to do that though!

As a half way measure, the `ORDER BY` could be changed to be by `users_games_hands.id` not `wcardidx`. `wcardidx` is the index of the card in the White Card deck. Since the game's deck is shuffled, the series of `wcardidx`s you get are completely random: Your new White Cards could appear anywhere in your hand, pushing higher-indexed cards down your hand.

For example, given the code at the moment, let's say your hand has the following indices:

| Position | wcardidx |
| --- | --- |
| 1 | 26 |
| 2 | 56 |
| 3 | 123 |
| 4 | 170 |
| 5 | 178 |
| 6 | 208 |
| 7 | 234 |
| 8 | 298 |
| 9 | 334 |
| 10 | 408 |

You play position 6.

Your next card:

``` SQL
SELECT
    cardidx
FROM
    wcards
WHERE
    game = $game->id
LIMIT 1;
```

```
cardidx
----------
108
```

So now your hand is:

| Position | wcardidx |
| --- | --- |
| 1 | 26 |
| 2 | 56 |
| 3 | 108 |
| 4 | 123 |
| 5 | 170 |
| 6 | 178 |
| 7 | 234 |
| 8 | 298 |
| 9 | 334 |
| 10 | 408 |

Card 108 got inserted at position 3 and everything else got shifted down one.

But on the other hand if it ordered by `u_g_h.id` your hand would start like this:

| Position | id | wcardidx |
| --- | --- | --- |
| 1 | 21 | 234 |
| 2 | 22 | 170 |
| 3 | 23 | 26 |
| 4 | 24 | 408 |
| 5 | 25 | 298 |
| 6 | 26 | 334 |
| 7 | 27 | 56 |
| 8 | 28 | 178 |
| 9 | 29 | 208 |
| 10 | 30 | 123 |

Play 208 (position 9) and get 108 back, then it looks like:

| Position | id | wcardidx |
| --- | --- | --- |
| 1 | 21 | 234 |
| 2 | 22 | 170 |
| 3 | 23 | 26 |
| 4 | 24 | 408 |
| 5 | 25 | 298 |
| 6 | 26 | 334 |
| 7 | 27 | 56 |
| 8 | 28 | 178 |
| 9 | 30 | 123 |
| 10 | 31 | 108 |

Do you see the difference? Cards "after" the one you play would get shifted up by one, and then the new card(s) would _always_ appear on the "end" of the hand.

That hasn't helped the "all the numbers in my hand changed" problem, because that's almost the same: cards "after" the one you play get shifted down.

But it _does_ help the "my new cards don't have numbers" problem, as they will have predictable positions: 1 new card is position 10, 2 new cards are positions 9 and 10, and so on.

Then again, is knowing those new numbers useful when all the rest of your hand has potentially changed number?

**Comment by Daviey** [comment]
I've been trying to ponder this, but every other idea I have come up with has side effect of moving other positions.  Would it be unreasonable to change the db schema to include a position reference?

**Comment by domcleal** [comment]
I think the position is necessary too.  When running the `topup_hand` routine, just pull back the list of current cards for the player, identify any positions in `1..10` that aren't present and insert rows with those position IDs.  (Maybe you can do a LEFT JOIN or NOT IN query to identify those in the DB, I'm not sure...)

A unique index over `(game, user, position)` or similar might be wise too.

**Comment by grifferz** [comment]
Thanks.

I agree that the re-ordering is very confusing and needs to be got rid of.

So yes there is probably no way out of this but database changes.
